<?php

/**
 * @file
 * Handles the creation/display of islandora:sp-document objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_document_menu() {
  return array(
    'admin/islandora/solution_pack_config/document' => array(
      'title' => 'Document Solution Pack',
      'description' => 'Define ingest behavior and configure document display.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_document_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_document_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_document' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora_document',
      'pattern' => 'islandora_document__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_document_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_document');
  // Document Content Model.
  $document_content_model = $connection->repository->constructObject('islandora:sp_document');
  $document_content_model->owner = 'fedoraAdmin';
  $document_content_model->label = 'Islandora Document Content Model';
  $document_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $document_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_document_ds_composite_model.xml", FALSE);
  $document_content_model->ingestDatastream($datastream);
  // ISLANDORA-CM Datastream.
  $datastream = $document_content_model->constructDatastream('ISLANDORACM', 'M');
  $datastream->label = 'Islandora content model information';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_document_content_model.xml", FALSE);
  $document_content_model->ingestDatastream($datastream);
  // Document Collection.
  $document_collection = $connection->repository->constructObject('islandora:sp_document_collection');
  $document_collection->owner = 'fedoraAdmin';
  $document_collection->label = 'Document Collection';
  $document_collection->models = 'islandora:collectionCModel';
  $document_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $document_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_document_collection_policy.xml", FALSE);
  $document_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $document_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $document_collection->ingestDatastream($datastream);
  return array(
    'islandora_document' => array(
      'title' => 'Islandora Document',
      'objects' => array(
        $document_content_model,
        $document_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_document_islandora_sp_document_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_document', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_xml_form_builder_forms().
 */
function islandora_document_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_document');
  return array(
    'Document MODS form' => array(
      'form_file' => "$module_path/xml/islandora_document_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_xml_form_builder_form_associations().
 */
function islandora_document_xml_form_builder_form_associations() {
  return array(
    'islandora_document_mods_form' => array(
      'content_model' => 'islandora:sp_document',
      'form_name' => 'Document MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_document_islandora_sp_document_islandora_ingest_steps() {
  return array(
    'islandora_document_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_document_document_upload_form',
      'module' => 'islandora_document',
      'file' => 'includes/document_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_derivative().
 */
function islandora_document_islandora_sp_document_islandora_derivative() {
  $derivatives = array();
  $derivatives[] = array(
    'source_dsid' => 'OBJ',
    'destination_dsid' => 'PDF',
    'weight' => '0',
    'function' => array(
      'islandora_document_add_pdf_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_document') . '/includes/derivatives.inc',
  );
  $derivatives[] = array(
    'source_dsid' => 'PDF',
    'destination_dsid' => 'TN',
    'weight' => '0',
    'function' => array(
      'islandora_document_add_tn_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_document') . '/includes/derivatives.inc',
  );
  $derivatives[] = array(
    'source_dsid' => 'PDF',
    'destination_dsid' => 'PREVIEW',
    'weight' => '1',
    'function' => array(
      'islandora_document_add_preview_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_document') . '/includes/derivatives.inc',
  );
  if (variable_get('islandora_document_create_fulltext', FALSE)) {
    $derivatives[] = array(
      'source_dsid' => 'PDF',
      'destination_dsid' => 'FULL_TEXT',
      'weight' => '2',
      'function' => array(
        'islandora_document_add_fulltext_derivative',
      ),
      'file' => drupal_get_path('module', 'islandora_document') . '/includes/derivatives.inc',
    );
  }
  return $derivatives;
}
